spring:
  application:
    name: zuul
  redis:
    host: 47.106.215.35
    port: 6379
  session:
    store-type: redis
server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
#  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    login-register:
      path: /loginAndRegister/**
      serviceId: login-register

    redis-service:
      path: /redisService/**
      serviceId: redis-service

    rabbitmq-service:
      path: /rabbitmqService/**
      serviceId: rabbitmq-service


    web-service:
      path: /Biri/**
      serviceId: web-service
  ignored-services: "*"
  sensitive-headers:
  host:
    connect-timeout-millis: 200000
    socket-timeout-millis: 200000
feign:
  httpclient:
    connection-timeout: 100000
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000








