spring:
  application:
    name: zuul
  redis:
    host: 47.106.215.35
    port: 6379
  session:
    store-type: redis
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://47.106.215.35:3306/Airi?useUnicode=true&characterEncoding=utf-8
server:
  port: 8769
  max-http-header-size: 102400
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
#  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    login-register:
      path: /loginAndRegister/**
      serviceId: login-register

    redis-service:
      path: /redisService/**
      serviceId: redis-service

    rabbitmq-service:
      path: /rabbitmqService/**
      serviceId: rabbitmq-service

    user-service:
      path: /userService/**
      serviceId: user-service

    book-service:
      path: /bookService/**
      serviceId: book-service

    comment-service:
      path: /commentService/**
      serviceId: comment-service

    web-service:
      path: /Biri/**
      serviceId: web-service

    order-cart:
      path: /orderCart/**
      serviceId: order-cart

    admin-service:
      path: /adminService/**
      serviceId: admin-service


  ignored-services: "*"
  sensitive-headers:
  host:
    connect-timeout-millis: 200000
    socket-timeout-millis: 200000
feign:
  httpclient:
    connection-timeout: 100000
    enabled: true
  hystrix:
    enabled: true
mybatis:
    mapper-locations: classpath:/mapperXML/*.xml
    configuration:
      cache-enabled: true

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000








