spring:
  application:
    name: zuul
  redis:
    host: 192.168.31.67
    port: 6379
  session:
    store-type: redis
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
#  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    login-register:
      path: /Biri/loginAndRegister/**
      serviceId: login-register


    redis-service:
          path: /Biri/redisSevice/**
          serviceId: redis-service
  ignored-services: "*"
  sensitive-headers: "*"