server:
  port: 8003
spring:
  application:
    name: book-service
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
eureka:
  instance:
    prefer-ip-address: true #注册服务时使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka